name: Testing Affected

on: [push, pull_request]

env:
    NX_WORKSPACE_ROOT_PATH: ./example

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nx-affected
        uses: vitorcamachoo/nx-affected-gh-action@master
        with:
          base: ${{ env.BRANCH_NAME }}
      - name: Print affected
        run: |
          echo affected: ${{ steps.nx-affected.outputs.affected }}
          echo affected-apps: ${{ steps.nx-affected.outputs.affected-apps }}
          echo affected-libs: ${{ steps.nx-affected.outputs.affected-libs }}